### ISSUE TITLE
vue-human/utils/Query.js

### ISSUE THREAD

**Issue by Youzhigang** [freshesx/humans#185]
输入数字, Query.parse方法会最终调用 lodash 的 toNumber方法,  lodash 中[代码](https://github.com/lodash/lodash/blob/d10b44bdef2b735865c493fbaec8687ec8998aef/toNumber.js#L56), 当输入身份证的时候, 太长了, 导致结果不对
```
a = '320158199012122433'
+a // 320158199012122430
```
实际上是js精确算数运算整数的范围-2^53~2^53. 18位的整数超出了这个范围

**Comment by minowu** [comment]
这的确是一个麻烦，后面把 Query 升级，允许为 Query 指定 key 采用不同的解析方法。
